apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vm-victoria-metrics-single-server
  namespace: victoria-module
  {{- include "helm_lib_module_labels" (list . (dict "app" "victoriametrics")) | nindent 2 }}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    {{- include "victoriametrics.selectorLabels" . | nindent 4 }}
  template:
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --retentionPeriod=1
        - --storageDataPath=/storage
        - -promscrape.config=/scrapeconfig/scrape.yml
        - --envflag.enable=true
        - --envflag.prefix=VM_
        - --loggerFormat=json
        - --promscrape.config=/etc/prometheus/prometheus.yml
        - --promscrape.configCheckInterval=15s
        image: victoriametrics/victoria-metrics:v1.88.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 8428
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: victoria-metrics-single-server
        ports:
        - containerPort: 8428
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /storage
          name: server-volume
        - mountPath: /scrapeconfig
          name: scrapeconfig
        - mountPath: /etc/prometheus/
          name: prometheus-config-volume
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: vm-victoria-metrics-single
      serviceAccountName: vm-victoria-metrics-single
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          defaultMode: 420
          name: vm-victoria-metrics-single-server-scrapeconfig
        name: scrapeconfig
      - configMap:
          defaultMode: 420
          name: prometheus-server-conf
        name: prometheus-config-volume
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: server-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      volumeMode: Filesystem